//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOSalad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salad
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Allergy { get; set; }
        public string Ingredients { get; set; }
        public string Preparation { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Location { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<System.DateTime> InsertDB { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> DeleteDB { get; set; }
    }
}
